[tool.poetry]
name = "kaggle-prediction-interval-birthweight"
version = "0.0.1"
description = "A small package with code for a kaggle competition."
authors = ["Hunter Merrill <hmerrill12@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
