[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kaggle-prediction-interval-birthweight"
version = "0.0.1"
authors = [
  {name="Hunter Merrill", email="hmerrill12@gmail.com"},
]
description = "A small package with code for a kaggle competition."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/hrmerrill/kaggle-prediction-interval-birthweight/"
